name: Node.js CI

on:
  push:
    branches: [ "_" ]
  pull_request:
    branches: [ "_" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install
    - run: bun run build
